[tool.poetry]
name = "aiida-n2p2"
version = "0.1.0a1"
description = "AiiDA plugin for n2p2 neural network potential package."
authors = ["Akshay Krishna Ammothum Kandy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."aiida.calculations"]
"n2p2.scale" = "aiida_n2p2.calculations.scaling:nnpScaling"
"n2p2.train" = "aiida_n2p2.calculations.train:nnpTraining"
"n2p2.predict"= "aiida_n2p2.calculations.predict:nnpPredict"

[tool.poetry.plugins."aiida.parsers"]
"n2p2.scale" = "aiida_n2p2.parsers.scaling:nnpScaleParser"
"n2p2.train" = "aiida_n2p2.parsers.train:nnpTrainParser"
"n2p2.predict" = "aiida_n2p2.parsers.predict:nnpPredictParser"

[tool.poetry.plugins."aiida.workflows"]
"n2p2.make_potential" = "aiida_n2p2.workflows.make_potential:MakeNNPWorkchain"

[tool.ruff]
line-length = 80
extend-exclude = ["examples"]
