[tool.poetry]
name = "aiida-n2p2"
version = "0.1.0a1"
description = "AiiDA plugin for n2p2 neural network potential package."
authors = ["Akshay Krishna Ammothum Kandy"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
