"""
Plugin for nnp-train in AiiDA-n2p2
"""

from aiida.common import datastructures
from aiida.engine import CalcJob, CalcJobProcessSpec
from aiida.orm import SinglefileData, Int


class nnpTraining(CalcJob):
    """AiiDA calculation plugin for training a potential

    Args:
        CalcJob (_type_): _description_

    """

    @classmethod
    def define(cls, spec: CalcJobProcessSpec):
        """ """
        super().define(spec)

        # set default values for AiiDA options
        spec.inputs["metadata"]["options"]["resources"].default = {
            "num_machines": 1,
            "num_mpiprocs_per_machine": 8,
        }

        spec.inputs["metadata"]["options"]["parser_name"].default = "n2p2.train"

        # new ports
        spec.input(
            "metadata.options.output_filename",
            valid_type=str,
            default="train.log",
        )
        spec.input(
            "atomicNumber", valid_type=Int, help="Atomic number of the element"
        )
        spec.input("inputData", valid_type=SinglefileData, help="Training set")
        spec.input(
            "inputNN",
            valid_type=SinglefileData,
            help="n2p2 config  file (*.nn) ",
        )
        spec.input("inputScale", valid_type=SinglefileData, help="Scaling data")
        # spec.output_namespace('weights', valid_type=SinglefileData, dynamic=False, help='Dynamic output files generated by nnp-train')
        spec.output(
            "weights",
            valid_type=SinglefileData,
            help="Weights for the optimal NN",
        )

    def prepare_for_submission(self, folder):
        """
        Create input files.

        :param folder: an `aiida.common.folders.Folder` where the plugin should temporarily place all files
            needed by the calculation.
        :return: `aiida.common.datastructures.CalcInfo` instance
        """
        codeinfo = datastructures.CodeInfo()
        codeinfo.cmdline_params = []
        codeinfo.code_uuid = self.inputs.code.uuid
        codeinfo.stdout_name = self.metadata.options.output_filename

        # Prepare a `CalcInfo` to be returned to the engine
        calcinfo = datastructures.CalcInfo()
        calcinfo.codes_info = [codeinfo]
        calcinfo.local_copy_list = [
            (
                self.inputs.inputData.uuid,
                self.inputs.inputData.filename,
                self.inputs.inputData.filename,
            ),
            (
                self.inputs.inputNN.uuid,
                self.inputs.inputNN.filename,
                self.inputs.inputNN.filename,
            ),
            (
                self.inputs.inputScale.uuid,
                self.inputs.inputScale.filename,
                "scaling.data",
            ),
        ]
        calcinfo.retrieve_list = ["learning-curve.out", "weight*.out"]

        return calcinfo
